export const generateBlogStats = () => ({
  totalPosts: 24,
  published: 18,
  drafts: 4,
  scheduled: 2,
  totalViews: 45600,
  totalComments: 328,
  totalLikes: 1240,
  averageReadTime: "5 min",
});

export const generateBlogPosts = () => [
  {
    _id: "blog_001",
    title:
      "Understanding Heart Disease: Early Warning Signs You Shouldn't Ignore",
    excerpt:
      "Heart disease remains the leading cause of death worldwide. Learn about the early warning signs that could save your life or the life of a loved one.",
    content: "",
    category: "Heart Health",
    tags: ["heart disease", "cardiology", "prevention", "symptoms"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "8 min",
    views: 2450,
    likes: 156,
    comments: 23,
    publishedDate: "2025-01-10",
    lastModified: "2025-01-10",
    featured: true,
  },
  {
    _id: "blog_002",
    title: "The Role of Diet in Managing Hypertension",
    excerpt:
      "Discover how dietary changes can significantly impact your blood pressure and reduce the need for medication.",
    content: "",
    category: "Nutrition",
    tags: ["hypertension", "diet", "blood pressure", "lifestyle"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "6 min",
    views: 1890,
    likes: 134,
    comments: 18,
    publishedDate: "2025-01-08",
    lastModified: "2025-01-09",
    featured: true,
  },
  {
    _id: "blog_003",
    title: "Cardiac Rehabilitation: A Complete Guide for Recovery",
    excerpt:
      "After a heart attack or surgery, cardiac rehabilitation is crucial. Here's everything you need to know about the recovery process.",
    content: "",
    category: "Recovery",
    tags: ["rehabilitation", "recovery", "heart surgery", "exercise"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "10 min",
    views: 3210,
    likes: 245,
    comments: 34,
    publishedDate: "2025-01-05",
    lastModified: "2025-01-06",
    featured: false,
  },
  {
    _id: "blog_004",
    title: "Stress and Heart Health: The Connection You Need to Know",
    excerpt:
      "Chronic stress can have devastating effects on your cardiovascular system. Learn how to protect your heart from stress-related damage.",
    content: "",
    category: "Mental Health",
    tags: ["stress", "mental health", "heart health", "wellness"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "7 min",
    views: 1560,
    likes: 98,
    comments: 15,
    publishedDate: "2025-01-02",
    lastModified: "2025-01-02",
    featured: false,
  },
  {
    _id: "blog_005",
    title: "Advances in Interventional Cardiology: What Patients Should Know",
    excerpt:
      "New technologies are revolutionizing heart treatments. Stay informed about the latest advances in interventional cardiology.",
    content: "",
    category: "Technology",
    tags: ["technology", "intervention", "treatment", "innovation"],
    author: "Dr. Stephen Conley",
    status: "draft",
    coverImage: null,
    readTime: "5 min",
    views: 0,
    likes: 0,
    comments: 0,
    publishedDate: null,
    lastModified: "2025-01-15",
    featured: false,
  },
  {
    _id: "blog_006",
    title: "Winter Heart Care: Tips for Cold Weather Cardiovascular Health",
    excerpt:
      "Cold weather can put extra strain on your heart. Follow these essential tips to keep your heart healthy during winter months.",
    content: "",
    category: "Seasonal Health",
    tags: ["winter", "seasonal", "prevention", "tips"],
    author: "Dr. Stephen Conley",
    status: "scheduled",
    coverImage: null,
    readTime: "6 min",
    views: 0,
    likes: 0,
    comments: 0,
    publishedDate: "2025-01-20",
    lastModified: "2025-01-14",
    featured: false,
  },
  {
    _id: "blog_007",
    title: "Understanding Cholesterol: Good vs Bad and How to Manage It",
    excerpt:
      "Cholesterol management is key to heart health. Learn the difference between LDL and HDL and how to maintain healthy levels.",
    content: "",
    category: "Heart Health",
    tags: ["cholesterol", "LDL", "HDL", "diet"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "7 min",
    views: 2800,
    likes: 210,
    comments: 28,
    publishedDate: "2024-12-28",
    lastModified: "2024-12-28",
    featured: true,
  },
  {
    _id: "blog_008",
    title: "Exercise and Your Heart: Finding the Right Balance",
    excerpt:
      "Physical activity is essential for heart health, but too much can be harmful. Find out how to exercise safely for optimal cardiovascular benefits.",
    content: "",
    category: "Fitness",
    tags: ["exercise", "fitness", "workout", "heart rate"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "9 min",
    views: 1950,
    likes: 167,
    comments: 22,
    publishedDate: "2024-12-20",
    lastModified: "2024-12-21",
    featured: false,
  },
  {
    _id: "blog_009",
    title: "The Impact of Sleep on Cardiovascular Health",
    excerpt:
      "Poor sleep quality is linked to heart disease. Discover the science behind sleep and how to improve your sleep habits for better heart health.",
    content: "",
    category: "Lifestyle",
    tags: ["sleep", "lifestyle", "wellness", "prevention"],
    author: "Dr. Stephen Conley",
    status: "draft",
    coverImage: null,
    readTime: "4 min",
    views: 0,
    likes: 0,
    comments: 0,
    publishedDate: null,
    lastModified: "2025-01-13",
    featured: false,
  },
  {
    _id: "blog_010",
    title: "Heart Disease in Women: Unique Symptoms and Risk Factors",
    excerpt:
      "Heart disease presents differently in women. Learn about the unique symptoms and risk factors that affect women's heart health.",
    content: "",
    category: "Women's Health",
    tags: ["women", "gender", "symptoms", "awareness"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "8 min",
    views: 3400,
    likes: 289,
    comments: 41,
    publishedDate: "2024-12-15",
    lastModified: "2024-12-16",
    featured: true,
  },
  {
    _id: "blog_011",
    title: "Smoking and Heart Disease: Breaking the Addiction",
    excerpt:
      "Smoking is one of the leading causes of heart disease. Find resources and strategies to quit smoking and protect your heart.",
    content: "",
    category: "Lifestyle",
    tags: ["smoking", "addiction", "prevention", "lifestyle"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "7 min",
    views: 1250,
    likes: 87,
    comments: 12,
    publishedDate: "2024-12-10",
    lastModified: "2024-12-10",
    featured: false,
  },
  {
    _id: "blog_012",
    title: "Telemedicine in Cardiology: The Future of Heart Care",
    excerpt:
      "Virtual consultations are changing how we deliver cardiac care. Explore the benefits and limitations of telemedicine in cardiology.",
    content: "",
    category: "Technology",
    tags: ["telemedicine", "virtual care", "technology", "future"],
    author: "Dr. Stephen Conley",
    status: "published",
    coverImage: null,
    readTime: "6 min",
    views: 980,
    likes: 76,
    comments: 9,
    publishedDate: "2024-12-05",
    lastModified: "2024-12-05",
    featured: false,
  },
];

export const generateCategories = () => [
  {
    name: "Heart Health",
    count: 8,
    color: "bg-red-100 dark:bg-red-900/20 text-red-700 dark:text-red-400",
  },
  {
    name: "Nutrition",
    count: 4,
    color:
      "bg-green-100 dark:bg-green-900/20 text-green-700 dark:text-green-400",
  },
  {
    name: "Fitness",
    count: 3,
    color: "bg-blue-100 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400",
  },
  {
    name: "Lifestyle",
    count: 5,
    color:
      "bg-purple-100 dark:bg-purple-900/20 text-purple-700 dark:text-purple-400",
  },
  {
    name: "Mental Health",
    count: 2,
    color:
      "bg-amber-100 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400",
  },
  {
    name: "Technology",
    count: 3,
    color: "bg-cyan-100 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400",
  },
  {
    name: "Recovery",
    count: 2,
    color: "bg-pink-100 dark:bg-pink-900/20 text-pink-700 dark:text-pink-400",
  },
  {
    name: "Women's Health",
    count: 2,
    color:
      "bg-indigo-100 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-400",
  },
  {
    name: "Seasonal Health",
    count: 2,
    color:
      "bg-orange-100 dark:bg-orange-900/20 text-orange-700 dark:text-orange-400",
  },
];

export const generatePopularTags = () => [
  { name: "heart disease", count: 6 },
  { name: "prevention", count: 5 },
  { name: "cardiology", count: 4 },
  { name: "lifestyle", count: 4 },
  { name: "diet", count: 3 },
  { name: "exercise", count: 3 },
  { name: "symptoms", count: 3 },
  { name: "treatment", count: 2 },
  { name: "technology", count: 2 },
  { name: "wellness", count: 2 },
];
