export const doctorInfo = {
  firstName: "Stephen",
  lastName: "Conley",
  specialty: "Cardiologist",
  email: "dr.stephen@mediscanai.com",
  phone: "(704) 555-0127",
  rating: 4.8,
  totalReviews: 146,
  trustPercentage: 95,
  experience: 15,
  totalPatients: 24400,
  clinicConsulting: 166300,
  totalAppointments: 53500,
};

export const generateAppointmentRequests = () => [
  {
    id: "appt1",
    patientName: "Bogdan Krivenchenko",
    age: 45,
    gender: "Male",
    date: "12 April",
    time: "9:30",
    status: "pending",
  },
  {
    id: "appt2",
    patientName: "Jenny Wilson",
    age: 32,
    gender: "Female",
    date: "25 April",
    time: "10:30 AM",
    status: "pending",
  },
  {
    id: "appt3",
    patientName: "Dianne Russel",
    age: 45,
    gender: "Male",
    date: "Today",
    time: "14:30 PM",
    status: "confirmed",
  },
  {
    id: "appt4",
    patientName: "Annette Black",
    age: 45,
    gender: "Male",
    date: "Today",
    time: "14:30 PM",
    status: "confirmed",
  },
  {
    id: "appt5",
    patientName: "Angelina Jully",
    age: 45,
    gender: "Male",
    date: "Today",
    time: "14:30 PM",
    status: "confirmed",
  },
  {
    id: "appt6",
    patientName: "Esther Howard",
    age: 45,
    gender: "Male",
    date: "Today",
    time: "14:30 PM",
    status: "declined",
  },
  {
    id: "appt7",
    patientName: "Robert Fox",
    age: 45,
    gender: "Male",
    date: "Today",
    time: "14:30 PM",
    status: "confirmed",
  },
];

export const generateTodayAppointments = () => [
  {
    id: "today1",
    patientName: "Jhon Smith",
    type: "Clinic Consulting",
    status: "Ongoing",
    time: "09:15",
  },
  {
    id: "today2",
    patientName: "Frank Murray",
    type: "Video Consulting",
    status: "Upcoming",
    time: "10:25",
  },
  {
    id: "today3",
    patientName: "Ella Lucia",
    type: "Emergency",
    status: "Upcoming",
    time: "11:30",
  },
  {
    id: "today4",
    patientName: "Alyssa Dehn",
    type: "Clinic Consulting",
    status: "Upcoming",
    time: "12:20",
  },
];

export const generateRecentPatients = () => [
  {
    id: "pat1",
    name: "Deveon Lane",
    visitId: "OPD-2345",
    date: "5/7/21",
    gender: "Male",
    disease: "Diabetes",
    status: "Out-Patient",
  },
  {
    id: "pat2",
    name: "Albert Flores",
    visitId: "IPD-2424",
    date: "5/7/21",
    gender: "Male",
    disease: "Diabetes",
    status: "Out-Patient",
  },
];

export const generateReviews = () => [
  {
    id: "rev1",
    name: "Ronald Richards",
    profession: "Engineer",
    date: "8 Jun, 2021",
    rating: 5,
    review:
      "Thank you to Dr. Stephen Conley and staff for a great experience right from the start. Everyone made me feel comfortable and the outcome was great. If you need heart surgery check out Dr. Stephen",
  },
  {
    id: "rev2",
    name: "Annette Black",
    profession: "Teacher",
    date: "8 Jun, 2021",
    rating: 5,
    review:
      "Dr. Stephen Conley did a great job on my knee! After my injection I was able to walk again without pain. Before His Injection I had 24 hour round the clock pain. Now, I can walk without any discomfort. Thank You Dr. Stephen Conley",
  },
  {
    id: "rev3",
    name: "Angelina Jully",
    profession: "Teacher",
    date: "8 Jun, 2021",
    rating: 5,
    review:
      "Excellent cardiologist, my husband and I have both had surgery and ongoing care from him over the years, the medical technology used is state of the art as well, continue to highly recommend.",
  },
  {
    id: "rev4",
    name: "Jane Cooper",
    profession: "Teacher",
    date: "8 Jun, 2021",
    rating: 5,
    review:
      "Excellent cardiologist, my husband and I have both had surgery and ongoing care from him over the years, the medical technology used is state of the art as well, continue to highly recommend.",
  },
];

export const generateMessages = () => [
  {
    id: "msg1",
    sender: "Jane Martin",
    message: "Good Morning, What's the matter jone?",
    time: "Today 7:55 am",
    unread: true,
    online: true,
  },
  {
    id: "msg2",
    sender: "John Smith",
    message: "I hope you get well soon",
    time: "17:10",
    unread: false,
    callType: "voice",
  },
  {
    id: "msg3",
    sender: "Hannah Smith",
    message: "I have prescribed for you...",
    time: "05-04-21",
    unread: false,
    callType: "voice",
  },
  {
    id: "msg4",
    sender: "Mr. Jhon Doe",
    message: "You need to do a lab check",
    time: "Yesterday",
    unread: false,
    attachment: true,
  },
  {
    id: "msg5",
    sender: "Linda G. Guthrie",
    message: "Okay, see you again Human",
    time: "Yesterday",
    unread: false,
    attachment: true,
  },
];

export const generatePatientsList = () => [
  {
    id: "pl1",
    firstName: "Jhone",
    lastName: "Martin",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    email: "info@patient.com",
    phone: "01767766336",
    status: "In-Treatment",
    payment: "Private Cash",
    dateOfJoining: "03/12/2021",
  },
  {
    id: "pl2",
    firstName: "Floyd",
    lastName: "Miles",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    email: "floyd@patient.com",
    phone: "01767766337",
    status: "Out-Patient",
    payment: "Paypal",
    dateOfJoining: "03/12/2021",
  },
  {
    id: "pl3",
    firstName: "Albert",
    lastName: "Flores",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    email: "albert@patient.com",
    phone: "01767766338",
    status: "Out-Patient",
    payment: "Private Cash",
    dateOfJoining: "03/12/2021",
  },
  {
    id: "pl4",
    firstName: "Jenny",
    lastName: "Wilson",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    email: "jenny@patient.com",
    phone: "01767766339",
    status: "In-Treatment",
    payment: "Paypal",
    dateOfJoining: "03/12/2021",
  },
  {
    id: "pl5",
    firstName: "Cody",
    lastName: "Fisher",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    email: "cody@patient.com",
    phone: "01767766340",
    status: "Out-Patient",
    payment: "Private Cash",
    dateOfJoining: "03/12/2021",
  },
];
